"""Admission faults and bounded recomputation against retained physical deals."""
import hashlib
import io
import json
from copy import deepcopy
from dataclasses import replace
from pathlib import Path

import pytest

from bj import __version__, cli, record, replay
from bj.core import RANKS, STANDARD
from test_ev_physical_reference import CASES, physical_reference

FIXTURE = Path(__file__).parent / 'fixtures/saved-decision-v1-7a38141.json'
FIXTURE_SHA256 = '28a9fdc931f8c6fdb19b099218d4204d45522dee86d6b936c6ea7016d648a4f1'


def _saved():
    return json.loads(FIXTURE.read_bytes())


def _change(saved, path, value):
    target = saved
    for key in path[:-1]:
        target = target[key]
    target[path[-1]] = value
    return saved


def _shoe(cards):
    return tuple(cards.count(rank) for rank in RANKS)


def _forbid_calculation(monkeypatch):
    def forbidden(*args, **kwargs):
        pytest.fail('record was not refused before calculation')
    monkeypatch.setattr(record, 'best_action', forbidden)


def test_immutable_pre_consumer_schema_v1_fixture():
    # Emitted on 2026-10-08 from exact old source 7a38141, not regenerated by
    # the candidate exporter. Private provenance retains the source hashes.
    raw = FIXTURE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == FIXTURE_SHA256
    assert replay.replay_json(raw)['status'] == 'agreement'


@pytest.mark.parametrize('cards,up,unseen,s17', CASES)
def test_recompute_uses_independent_tiny_physical_reference(cards, up, unseen, s17):
    saved = record.decision_json(cards, up, replace(STANDARD, s17=s17), shoe=_shoe(unseen))
    result = replay.replay_json(saved)
    expected = physical_reference(cards, up, unseen, s17=s17)
    assert result['status'] == 'agreement'
    assert result['recomputed']['evs'] == pytest.approx(
        {key: float(value) for key, value in expected.items()}, rel=0, abs=1e-12)
    assert result['comparison']['legal_actions']['matches']
    assert result['comparison']['recommendation']['matches']
    assert result['comparison']['margin']['matches']


def test_fresh_origin_retains_counts_and_never_removes_visible_cards_again(monkeypatch):
    saved = record.decision_record('A,T', '9', replace(STANDARD, decks=1, blackjack_payout=1.25))
    expected = tuple(saved['state']['shoe']['counts'])
    original = record.best_action
    calls = []

    def checked(cards, up, *, shoe, rules, is_split_hand, hand_count,
                can_double, can_split):
        calls.append((cards, up, shoe, rules, is_split_hand, hand_count))
        assert shoe == expected
        return original(cards, up, shoe=shoe, rules=rules,
                        is_split_hand=is_split_hand, hand_count=hand_count,
                        can_double=can_double, can_split=can_split)

    monkeypatch.setattr(record, 'best_action', checked)
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'agreement'
    assert len(calls) == 1
    assert result['recomputed']['evs'] == {'S': 1.25}


@pytest.mark.parametrize('cards,up,unseen,changes,hand_count', [
    ('A,T', 'T', ('9',), {'das': False, 'max_hands': 2}, 2),
    ('8,8', 'T', ('7', '8', '9', 'T'), {'das': False, 'max_hands': 2}, 2),
    ('A,A', 'T', ('9', 'T', 'T'), {'resplit_aces': True, 'max_hands': 3}, 2),
    ('A,5,5', '6', ('T', 'T'), {'hit_split_aces': True, 's17': False}, 2),
])
def test_supported_split_state_replays_without_expanding_model(
        cards, up, unseen, changes, hand_count):
    saved = record.decision_record(cards, up, replace(STANDARD, **changes), shoe=_shoe(unseen),
                                   is_split_hand=True, hand_count=hand_count)
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'agreement'
    assert result['modeled_input']['rules'] == saved['rules']
    assert result['modeled_input']['state']['cards'] == saved['state']['cards']
    assert result['modeled_input']['state']['hand_count'] == hand_count


def test_first_split_card_order_remains_meaningful():
    saved = record.decision_record('A,7', 'T', shoe=_shoe(('8', '9', 'T')),
                                   is_split_hand=True, hand_count=2)
    assert replay.replay_json(json.dumps(saved))['status'] == 'agreement'
    saved['state']['cards'].reverse()  # Still total18/soft, now a split seven.
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'differences'
    assert result['modeled_input']['state']['cards'] == ['7', 'A']
    assert result['comparison']['legal_actions']['recomputed'] == ['D', 'H', 'S']


def test_consistently_changed_state_is_priced_instead_of_copying_saved_answer():
    saved = _saved()
    cards, up, unseen, s17 = CASES[6]
    saved['state']['cards'] = list(cards)
    saved['state']['total'], saved['state']['soft'] = 11, False
    saved['state']['shoe']['counts'] = list(_shoe(unseen))
    result = replay.replay_json(json.dumps(saved))
    expected = physical_reference(cards, up, unseen, s17=s17)
    assert result['status'] == 'differences'
    assert result['recorded'] == saved['decision']
    assert result['recomputed']['evs'] == pytest.approx(
        {key: float(value) for key, value in expected.items()}, rel=0, abs=1e-12)
    assert result['recomputed'] != result['recorded']


def test_supplied_counts_can_exceed_fresh_deck_maxima():
    saved = record.decision_record('A,T', '9', replace(STANDARD, decks=1),
                                   shoe=(0, 0, 0, 0, 0, 0, 0, 0, 0, 17))
    assert replay.replay_json(json.dumps(saved))['status'] == 'agreement'


@pytest.mark.parametrize('path,value', [
    (('decision', 'evs', 'H'), 123.0),
    (('decision', 'margin'), 0.0000000000000001),
    (('decision', 'action'), 'S'),
])
def test_altered_stored_answers_are_comparison_data(path, value):
    saved = _change(_saved(), path, value)
    if path[-1] == 'action':
        saved['decision']['action_name'] = 'STAND'
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'differences'
    assert result['recorded'] == saved['decision']
    assert result['recomputed'] == _saved()['decision']


def test_supported_action_set_difference_is_compared_not_rejected():
    saved = _saved()
    del saved['decision']['evs']['D']
    saved['decision']['evs']['P'] = 0.0
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'differences'
    assert result['comparison']['legal_actions'] == {
        'recorded': ['H', 'P', 'S'], 'recomputed': ['D', 'H', 'S'], 'matches': False}
    assert result['comparison']['evs']['D']['recorded'] is None
    assert result['comparison']['evs']['P']['recomputed'] is None


def test_action_identity_and_one_ulp_difference_are_never_hidden(monkeypatch):
    saved = _saved()
    saved['decision'].update(action='H', action_name='HIT', evs={'S': 0.0, 'H': 1e-16},
                             margin=1e-16)
    monkeypatch.setattr(record, 'best_action', lambda *a, **kw: (
        'S', {'S': 1e-16, 'H': 0.0}, 1e-16))
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'differences'
    assert not result['comparison']['recommendation']['matches']
    assert result['comparison']['margin']['matches']
    assert result['comparison_policy']['absolute_tolerance'] == 0
    assert '1e-16' in cli._replay_text(result)
    assert "recomputed 'S', matches=False" in cli._replay_text(result)


@pytest.mark.parametrize('path,value', [
    (('extra',), 'unknown'), (('rules', 'extra'), 1),
    (('state', 'shoe', 'extra'), 1), (('model', 'extra'), 1),
    (('schema', 'version'), True), (('schema', 'version'), 1.0),
    (('package', 'version'), 1), (('state', 'cards'), [True, 'T']),
    (('state', 'cards'), ['K', '4']), (('state', 'cards'), ['T']),
    (('state', 'cards'), ['T', 'T', 'T']), (('state', 'dealer_up'), True),
    (('state', 'total'), 15), (('state', 'total'), True),
    (('state', 'soft'), True), (('state', 'soft'), 0),
    (('state', 'hand_count'), None), (('state', 'hand_count'), True),
    (('state', 'hand_count'), 2), (('state', 'is_split_hand'), 1),
    (('state', 'shoe', 'counts'), [True] + [1] * 9),
    (('state', 'shoe', 'counts'), [1.0] * 10),
    (('state', 'shoe', 'counts'), [1] * 9),
    (('state', 'shoe', 'counts'), [0] * 10),
    (('state', 'shoe', 'counts'), [1] + [0] * 9),
    (('state', 'shoe', 'rank_order'), list(reversed(RANKS))),
    (('state', 'shoe', 'includes_hidden_hole'), 1),
    (('rules', 'decks'), True), (('rules', 'max_hands'), 0),
    (('rules', 's17'), 1), (('rules', 'blackjack_payout'), True),
    (('rules', 'blackjack_payout'), 10 ** 400),
    (('rules', 'insurance_payout'), 10 ** 400),
    (('rules', 'insurance_payout'), -1),
    (('model', 'hole_rank_excluded_by_peek'), 'T'),
    (('model', 'insurance_priced'), 0),
    (('decision', 'action_name'), 'STAND'), (('decision', 'action'), 'X'),
    (('decision', 'evs'), {'X': 0}), (('decision', 'evs'), []),
    (('decision', 'evs'), {'S': 0.0}), (('decision', 'evs', 'H'), True),
    (('decision', 'evs', 'H'), 10 ** 400),
    (('decision', 'margin'), True), (('decision', 'margin'), -1),
])
def test_invalid_fields_are_refused_before_calculation(monkeypatch, path, value):
    _forbid_calculation(monkeypatch)
    result = replay.replay_json(json.dumps(_change(_saved(), path, value)))
    assert result['status'] == 'invalid_input'
    assert result['recomputed'] is None and result['comparison'] is None


@pytest.mark.parametrize('path,value', [
    (('schema', 'name'), 'other'), (('schema', 'version'), 4),
    (('rules', 'peek'), False), (('rules', 'surrender'), True),
    (('rules', 'double_any_two'), False), (('rules', 'tens_are_pairs'), False),
    (('model', 'dealer_information'), 'known_hole'),
    (('model', 'split'), 'joint_exact'), (('model', 'split_error_bound'), 0.0),
    (('model', 'insurance_priced'), True), (('decision', 'units'), 'percent'),
    (('decision', 'whole_game_estimate'), 0.0),
    (('state', 'shoe', 'includes_hidden_hole'), False),
    (('state', 'shoe', 'visible_cards_already_removed'), False),
    (('state', 'shoe', 'source'), 'unknown'),
])
def test_unsupported_schema_or_model_refused_before_calculation(monkeypatch, path, value):
    _forbid_calculation(monkeypatch)
    result = replay.replay_json(json.dumps(_change(_saved(), path, value)))
    assert result['status'] == 'unsupported_record'


@pytest.mark.parametrize('text', [
    '', '[]', '{', '{"schema":{"name":"blackjack-decision","version":1,"version":1}}',
    '{"x":NaN}', '{"x":Infinity}', '{"x":-Infinity}', '{"x":1e999}',
    '[' * (replay.MAX_RECORD_DEPTH + 1) + '0' + ']' * (replay.MAX_RECORD_DEPTH + 1),
    ' ' * (replay.MAX_RECORD_BYTES + 1), b'\xff', None,
], ids=['empty', 'array', 'malformed', 'duplicate-schema', 'nan', 'infinity',
        'negative-infinity', 'overflow', 'deep', 'oversize', 'utf8', 'not-text'])
def test_json_admission_limits_are_checked_before_calculation(monkeypatch, text):
    _forbid_calculation(monkeypatch)
    assert replay.replay_json(text)['status'] == 'invalid_input'


def test_nested_duplicate_is_refused_before_calculation(monkeypatch):
    _forbid_calculation(monkeypatch)
    text = FIXTURE.read_text().replace('"decks": 6', '"decks": 6, "decks": 6')
    assert replay.replay_json(text)['status'] == 'invalid_input'


def test_missing_field_and_inconsistent_fresh_origin_refused(monkeypatch):
    saved = _saved()
    del saved['rules']['s17']
    _forbid_calculation(monkeypatch)
    assert replay.replay_json(json.dumps(saved))['status'] == 'invalid_input'
    saved = _saved()
    saved['state']['shoe']['source'] = 'fresh_minus_visible'
    assert replay.replay_json(json.dumps(saved))['status'] == 'invalid_input'


def test_package_version_is_a_label_and_not_an_origin_or_install_instruction():
    saved = _saved()
    saved['package']['version'] = 'other-version [{{{{{{{{{{ escaped " label'
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'agreement'
    assert result['package_version_matches'] is False
    assert result['current_package']['version'] == __version__


def test_field_order_whitespace_and_utf8_do_not_change_interpretation():
    saved = _saved()
    expected = replay.replay_json(json.dumps(saved))
    for text in (json.dumps(saved, sort_keys=True, indent=4),
                 json.dumps(saved, separators=(',', ':')).encode('utf-8')):
        assert replay.replay_json(text) == expected


@pytest.mark.parametrize('exc,status', [(KeyboardInterrupt(), 'interrupted'),
                                      (MemoryError(), 'resource_limited'),
                                      (RecursionError(), 'resource_limited'),
                                      (OverflowError(), 'calculation_error')])
def test_incomplete_execution_is_not_a_mismatch(monkeypatch, exc, status):
    def incomplete(*args, **kwargs):
        raise exc
    monkeypatch.setattr(record, 'best_action', incomplete)
    result = replay.replay_json(FIXTURE.read_bytes())
    assert result['status'] == status
    assert result['recorded'] == _saved()['decision']
    assert result['recomputed'] is None and result['comparison'] is None


def test_admitted_dealer_draw_shortage_is_calculation_error():
    saved = _saved()
    saved['state'].update(cards=['T', '6'], total=16, dealer_up='6')
    saved['state']['shoe']['counts'] = list(_shoe(('2',)))
    saved['model']['hole_rank_excluded_by_peek'] = None
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'calculation_error'
    assert 'shoe is empty' in result['error']['message']
    assert result['comparison'] is None


def test_admitted_large_supplied_count_retains_data_on_engine_overflow():
    saved = _saved()
    saved['state']['shoe']['counts'] = [0] * 9 + [10 ** 400]
    result = replay.replay_json(json.dumps(saved))
    assert result['status'] == 'calculation_error'
    assert result['error']['type'] == 'OverflowError'
    assert result['recorded'] == saved['decision']
    assert result['modeled_input']['state']['shoe']['counts'] == [0] * 9 + [10 ** 400]
    assert result['recomputed'] is None and result['comparison'] is None


def test_file_read_is_bounded_and_does_not_change_bytes(tmp_path, monkeypatch):
    path = tmp_path / 'saved.json'
    original = FIXTURE.read_bytes()
    path.write_bytes(original)
    before = path.stat().st_mtime_ns
    assert replay.replay_file(path)['status'] == 'agreement'
    assert path.read_bytes() == original and path.stat().st_mtime_ns == before
    reads = []

    class Stream(io.BytesIO):
        def read(self, size=-1):
            reads.append(size)
            return super().read(size)

    monkeypatch.setattr(replay, 'open', lambda *a: Stream(b' ' * (replay.MAX_RECORD_BYTES + 10)),
                        raising=False)
    assert replay.replay_file(path)['status'] == 'invalid_input'
    assert reads == [replay.MAX_RECORD_BYTES + 1]


def test_cli_json_and_legacy_explicit_report_do_not_compute_whole_game(tmp_path, monkeypatch,
                                                                    capsys):
    def forbidden(*args, **kwargs):
        pytest.fail('unrelated whole-game computation')
    monkeypatch.setattr(cli, 'house_edge', forbidden)
    path = tmp_path / 'saved.json'
    path.write_bytes(FIXTURE.read_bytes())
    assert cli.main(['--replay', str(path), '--json']) == 0
    output = capsys.readouterr()
    assert output.err == ''
    assert json.loads(output.out)['status'] == 'agreement'
    assert cli.main(['T,4', 'T', '--unseen', '2,3,7,8,9,T']) == 0
    assert capsys.readouterr().out == cli.advise(
        'T,4', 'T', shoe=_shoe(('2', '3', '7', '8', '9', 'T'))) + '\n'


def test_legacy_cli_default_arguments_are_preserved_without_large_calculation(monkeypatch,
                                                                            capsys):
    calls = []

    def advice(cards, up, rules, **state):
        calls.append((cards, up, rules, state))
        return 'legacy advice'

    monkeypatch.setattr(cli, 'advise', advice)
    assert cli.main([]) == 0
    assert calls == [('8,8', 'T', STANDARD,
                      {'shoe': None, 'is_split_hand': False, 'hand_count': 1,
                       'can_double': True, 'can_split': True})]
    assert capsys.readouterr().out == 'legacy advice\n'


@pytest.mark.parametrize('options', [['T,4'], ['--table'], ['--decks', '6'], ['--h17'],
                                    ['--no-das'], ['--unseen', '9'], ['--split-hand'],
                                    ['--hand-count', '1']])
def test_cli_replay_conflicts_are_usage_errors_before_reading(monkeypatch, options, capsys):
    def forbidden(*args, **kwargs):
        pytest.fail('conflicting invocation read a record')
    monkeypatch.setattr(cli, 'replay_file', forbidden)
    with pytest.raises(SystemExit) as exc:
        cli.main(['--replay', 'not-read.json', *options])
    assert exc.value.code == 2
    assert capsys.readouterr().out == ''


@pytest.mark.parametrize('status,expected', list(replay.EXIT_STATUSES.items()))
def test_cli_returns_documented_outcome_status(monkeypatch, capsys, status, expected):
    result = replay._report(status)
    monkeypatch.setattr(cli, 'replay_file', lambda path: result)
    assert cli.main(['--replay', 'fixture.json', '--json']) == expected
    output = capsys.readouterr()
    assert not output.err
    assert json.loads(output.out)['status'] == status


def test_file_io_error_has_separate_outcome(tmp_path):
    result = replay.replay_file(tmp_path / 'missing.json')
    assert result['status'] == 'io_error'
    assert result['recorded'] is None


@pytest.mark.parametrize('path', [True, 0, None, b'record.json', 'invalid\0path'])
def test_file_api_does_not_treat_a_number_as_a_descriptor(path):
    assert replay.replay_file(path)['status'] == 'invalid_input'


def test_replay_does_not_mutate_a_python_record():
    saved = _saved()
    before = deepcopy(saved)
    replay.replay_json(json.dumps(saved))
    assert saved == before


@pytest.mark.parametrize('can_double,can_split', [
    (True, True), (False, True), (True, False), (False, False),
])
def test_controlled_replay_prices_once_and_preserves_saved_state(
        monkeypatch, can_double, can_split):
    counts = (1,) + (0,) * 8 + (5,)
    saved = record.decision_record('T,T', '7', replace(STANDARD, max_hands=2),
                                    shoe=counts, can_double=can_double,
                                    can_split=can_split)
    before = deepcopy(saved)
    original = record.decision_record
    calls = []

    def checked(cards, up, rules, **state):
        calls.append((cards, up, rules, state))
        assert state['shoe'] == counts
        assert state['can_double'] is can_double and state['can_split'] is can_split
        return original(cards, up, rules, **state)

    monkeypatch.setattr(record, 'decision_record', checked)
    report = replay.replay_json(json.dumps(saved))
    assert len(calls) == 1
    assert report['status'] == 'agreement'
    assert report['modeled_input']['state'] == before['state']
    assert report['recorded'] == report['recomputed'] == saved['decision']
    assert saved == before


def test_declared_version_two_true_true_replays_without_mutating_version_one():
    saved = _saved()
    saved['schema']['version'] = 2
    saved['state']['action_controls'] = {'can_split': True, 'can_double': True}
    before = deepcopy(saved)
    report = replay.replay_json(json.dumps(saved))
    assert report['status'] == 'agreement'
    assert report['modeled_input']['state'] == before['state']
    assert saved == before
    legacy = _saved()
    assert 'action_controls' not in replay.replay_json(json.dumps(legacy))['modeled_input']['state']


@pytest.mark.parametrize('controls', [
    None, True, [], 0, 'false', {}, {'can_double': True},
    {'can_double': True, 'can_split': True, 'unknown': False},
    {'can_double': 0, 'can_split': True}, {'can_double': True, 'can_split': 1},
    {'can_double': 'false', 'can_split': False},
])
def test_malformed_version_two_controls_refuse_before_pricing(monkeypatch, controls):
    _forbid_calculation(monkeypatch)
    saved = _saved()
    saved['schema']['version'] = 2
    saved['state']['action_controls'] = controls
    assert replay.replay_json(json.dumps(saved))['status'] == 'invalid_input'


def test_controls_missing_for_v2_extra_for_v1_and_duplicate_refuse_before_pricing(monkeypatch):
    _forbid_calculation(monkeypatch)
    missing = _saved()
    missing['schema']['version'] = 2
    assert replay.replay_json(json.dumps(missing))['status'] == 'invalid_input'
    extra = _saved()
    extra['state']['action_controls'] = {'can_double': True, 'can_split': True}
    assert replay.replay_json(json.dumps(extra))['status'] == 'invalid_input'
    extra['schema']['version'] = 2
    duplicate = json.dumps(extra).replace(
        '"can_double": true', '"can_double": true, "\\u0063an_double": false')
    report = replay.replay_json(duplicate)
    assert report['status'] == 'invalid_input'
    assert 'duplicate' in report['error']['message']


def test_saved_disabled_recommendation_remains_visible_comparison_data():
    saved = record.decision_record('T,4', 'T', shoe=_shoe(('2', '3', '7', '8', '9', 'T')),
                                    can_double=False)
    saved['decision']['evs']['D'] = 99.0
    saved['decision']['action'] = 'D'
    saved['decision']['action_name'] = 'DOUBLE'
    saved['decision']['margin'] = 88.0
    report = replay.replay_json(json.dumps(saved))
    assert report['status'] == 'differences'
    assert report['recorded'] == saved['decision']
    assert 'D' not in report['recomputed']['evs']
    assert not report['comparison']['legal_actions']['matches']
